version: 2
jobs:
  build:
    docker:
      - image: mhart/alpine-node:8.9.4
    working_directory: ~/3akai-ux
    steps:
      - run:
          name: Install dependencies
          command: >
            apk add --update --no-cache
            git
            openssh-client
      - checkout
      - run:
          name: Install NPM 4.6.1
          # default npm version is 5 and it doesn't work
          command: npm install --silent --global npm@4.6.1
      - run:
          name: Install Grunt
          command: npm install --silent --global grunt grunt-cli
      - run:
          name: Install NPM dependencies
          command: npm install --silent
      - run:
          name: Production build
          command: grunt
      # - run: grunt jshint
