version: 2
jobs:
  build:
    docker:
      - image: node:10-alpine
    working_directory: ~/3akai-ux
    steps:
      - run:
          name: Install dependencies
          command: >
            apk add --update --no-cache
            git
            openssh-client
      - checkout
      - run:
          name: Install Grunt
          command: yarn install --silent grunt grunt-cli
      - run:
          name: Install NPM dependencies
          command: npx lerna bootstrap
      - run:
          name: Production build
          command: npx grunt
      - run:
          name: Linting
          command: npx grunt jshint
